services:
#  lajko:
#    build: .
#    ports:
#      - 2137:2137
#    environment:
#      - DATABASE_URL=postgres://dev-user:dev-password@localhost:5432/lajko
#    depends_on:
#      - postgres
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/lajko-data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dev-password
      - POSTGRES_USER=dev-user
      - POSTGRES_DB=lajko