services:
  wombat:
    build: .
    ports:
      - 2137:2137
    environment:
      - DATABASE_URL=postgres://dev-user:dev-password@localhost:5432/wombat
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/wombat-data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dev-password
      - POSTGRES_USER=dev-user
      - POSTGRES_DB=wombat