apiVersion: apps/v1
kind: Deployment
metadata:
  name: wombat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wombat
  template:
    metadata:
      labels:
        app: wombat
    spec:
      containers:
        - name: wombat
          image: wombatdaiquiri/wombat:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: wombat
spec:
  selector:
    app: wombat
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080