global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "wombat"
    scrape_interval: 1m
    scheme: https
    static_configs:
      - targets: ["wombat:42069"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

remote_write:
  - url: "https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push"
    basic_auth:
      username: "745151"
      password: "eyJrIjoiNzEzZjEyOTE1OTJiNjdhODYwM2FmMWIzMTYzZmFmNzQ5YjZjZGM5NCIsIm4iOiJtb2JpbGUtd29tYmF0c3RhdGlvbiIsImlkIjo3ODI2Nzh9"
